use std::collections::HashMap;

use super::scoring::entity_score_value;
use super::*;
use crate::game::command::SimCommand as Command;
use crate::game::entity::{Entity, EntityKind, GatherPhase, Order, OrderIntent, WeaponSetup};
use crate::protocol::{kinds, terrain, AbilityCooldownView, EntityView, Event, OrderPlanMarker};
use crate::rules::{combat, terrain::TerrainKind};

mod ability_runtime_tests;
mod ai_identity_tests;
mod artillery_blanket_tests;
mod artillery_tests;
mod at_gun_firing_reveal_tests;
mod build_wait_tests;
mod checkpoint_helpers;
mod checkpoint_lab_tests;
mod checkpoint_payload_tests;
mod checkpoint_start_tests;
mod checkpoint_visibility_tests;
mod derived_state_tests;
mod determinism_tests;
mod ekat_tests;
mod faction_ability_tests;
mod fixtures;
mod meth_movement_tests;
mod mortar_manual_fire_tests;
mod movement_replay_tests;
mod panzerfaust_upgrade_tests;
mod primary_base_tests;
mod repeat_production_tests;
mod replay_artifact_tests;
mod resources_mining_tests;
mod road_terrain_tests;
mod scoring_projection_tests;
mod smoke_mortar_tests;
mod smoke_mortar_visibility_tests;
mod tank_trap_tests;
