//! Ability effect and cooldown constants exported through the balance surface.

use super::TICK_HZ;

pub const BREAKTHROUGH_RADIUS_TILES: f32 = 9.0;
pub const BREAKTHROUGH_DURATION_TICKS: u16 = (TICK_HZ as u16) * 6;
pub const BREAKTHROUGH_COOLDOWN_TICKS: u16 = (TICK_HZ as u16) * 25;
/// Permanent nearby-owned-unit movement multiplier from each Command Car.
pub const COMMAND_CAR_AURA_SPEED_MULTIPLIER: f32 = 1.4;
pub const BREAKTHROUGH_BASE_SPEED_MULTIPLIER: f32 = 1.8;
pub const BREAKTHROUGH_SMOKE_SPEED_MULTIPLIER: f32 = 2.2;
pub const BREAKTHROUGH_RECENT_SMOKE_TICKS: u16 = (TICK_HZ as u16) * 2;

pub const SMOKE_ABILITY_RANGE_TILES: u32 = 14;
pub const SMOKE_LAUNCH_MAX_DELAY_TICKS: u32 = TICK_HZ / 10;
pub const SMOKE_CLOUD_RADIUS_TILES: f32 = 2.0;
pub const SMOKE_CLOUD_DURATION_TICKS: u32 = TICK_HZ * 5;
pub const SMOKE_PLUS_CLOUD_RADIUS_TILES: f32 = SMOKE_CLOUD_RADIUS_TILES * 1.5;
pub const SMOKE_PLUS_CLOUD_DURATION_TICKS: u32 = SMOKE_CLOUD_DURATION_TICKS * 2;
pub const SMOKE_ABILITY_COOLDOWN_TICKS: u16 = 0;
pub const SCOUT_CAR_SMOKE_USES: u16 = 2;
pub const SMOKE_ABILITY_COST_STEEL: u32 = 0;
pub const SMOKE_ABILITY_COST_OIL: u32 = 0;

pub const ARTILLERY_BLANKET_RADIUS_TILES: f32 = 15.0;

pub const EKAT_CONSUME_GOLEM_RANGE_TILES: u32 = 2;
pub const EKAT_TELEPORT_RANGE_TILES: u32 = 5;
pub const EKAT_TELEPORT_COOLDOWN_TICKS: u16 = (TICK_HZ as u16) * 8;
pub const EKAT_RETURN_MARKER_DURATION_TICKS: u32 = TICK_HZ * 4;
pub const EKAT_RETURN_MIN_DELAY_TICKS: u32 = 1;
pub const EKAT_LINE_SHOT_RANGE_TILES: u32 = 6;
pub const EKAT_LINE_SHOT_WIDTH_TILES: f32 = 0.6;
pub const EKAT_LINE_SHOT_SPEED_PX_PER_TICK: f32 = 8.0;
pub const EKAT_LINE_SHOT_DAMAGE: u32 = 40;
pub const EKAT_LINE_SHOT_COOLDOWN_TICKS: u16 = (TICK_HZ as u16) * 10;
pub const EKAT_MAGIC_ANCHOR_RANGE_TILES: u32 = 5;
pub const EKAT_MAGIC_ANCHOR_DURATION_TICKS: u32 = TICK_HZ * 10;
pub const EKAT_MAGIC_ANCHOR_RADIUS_TILES: f32 = 3.0;
pub const EKAT_MAGIC_ANCHOR_PULL_AWAY_MULTIPLIER: f32 = 0.45;
pub const EKAT_MAGIC_ANCHOR_PULL_TOWARD_MULTIPLIER: f32 = 1.35;
