//! Vehicle and support-weapon body dimensions mirrored for collision/render previews.

pub const TANK_BODY_LENGTH_PX: f32 = 50.4;
pub const TANK_BODY_WIDTH_PX: f32 = 28.8;
pub const TANK_BODY_CLEARANCE_PX: f32 = 1.5;
pub const ANTI_TANK_GUN_BODY_LENGTH_PX: f32 = 42.0;
pub const ANTI_TANK_GUN_BODY_WIDTH_PX: f32 = 24.0;
pub const ANTI_TANK_GUN_BODY_CLEARANCE_PX: f32 = 1.0;
pub const ARTILLERY_BODY_SCALE: f32 = 0.75;
pub const ARTILLERY_BODY_LENGTH_PX: f32 = TANK_BODY_LENGTH_PX * ARTILLERY_BODY_SCALE;
pub const ARTILLERY_BODY_WIDTH_PX: f32 = TANK_BODY_WIDTH_PX * ARTILLERY_BODY_SCALE;
pub const ARTILLERY_BODY_CLEARANCE_PX: f32 = TANK_BODY_CLEARANCE_PX * ARTILLERY_BODY_SCALE;
pub const ARTILLERY_SELECTION_RADIUS_PX: f32 = 18.0 * ARTILLERY_BODY_SCALE;
pub const SCOUT_CAR_BODY_LENGTH_PX: f32 = 40.8;
pub const SCOUT_CAR_BODY_WIDTH_PX: f32 = 21.6;
pub const SCOUT_CAR_BODY_CLEARANCE_PX: f32 = 1.0;
pub const COMMAND_CAR_BODY_LENGTH_PX: f32 = 34.8;
pub const COMMAND_CAR_BODY_WIDTH_PX: f32 = 18.4;
pub const COMMAND_CAR_BODY_CLEARANCE_PX: f32 = 1.0;
