//! Upgrade costs and research durations.

use super::TICK_HZ;

pub const METHAMPHETAMINES_COST_STEEL: u32 = 100;
pub const METHAMPHETAMINES_COST_OIL: u32 = 100;
pub const METHAMPHETAMINES_RESEARCH_TICKS: u32 = TICK_HZ * 20;
pub const METHAMPHETAMINES_ATTACK_COOLDOWN_NUMERATOR: u32 = 3;
pub const METHAMPHETAMINES_ATTACK_COOLDOWN_DENOMINATOR: u32 = 4;
pub const ANTI_TANK_GUN_UNLOCK_COST_STEEL: u32 = 200;
pub const ANTI_TANK_GUN_UNLOCK_COST_OIL: u32 = 75;
pub const ANTI_TANK_GUN_UNLOCK_RESEARCH_TICKS: u32 = TICK_HZ * 20;
pub const ARTILLERY_UNLOCK_COST_STEEL: u32 = 300;
pub const ARTILLERY_UNLOCK_COST_OIL: u32 = 200;
pub const ARTILLERY_UNLOCK_RESEARCH_TICKS: u32 = TICK_HZ * 30;
pub const TANK_UNLOCK_COST_STEEL: u32 = 150;
pub const TANK_UNLOCK_COST_OIL: u32 = 100;
pub const TANK_UNLOCK_RESEARCH_TICKS: u32 = TICK_HZ * 20;
pub const COMMAND_CAR_UNLOCK_COST_STEEL: u32 = 150;
pub const COMMAND_CAR_UNLOCK_COST_OIL: u32 = 150;
pub const COMMAND_CAR_UNLOCK_RESEARCH_TICKS: u32 = TICK_HZ * 30;
pub const MORTAR_AUTOCAST_COST_STEEL: u32 = 150;
pub const MORTAR_AUTOCAST_COST_OIL: u32 = 150;
pub const MORTAR_AUTOCAST_RESEARCH_TICKS: u32 = TICK_HZ * 20;
