//! Upgrade costs and research durations.

use super::TICK_HZ;

pub const METHAMPHETAMINES_COST_STEEL: u32 = 100;
pub const METHAMPHETAMINES_COST_OIL: u32 = 100;
pub const METHAMPHETAMINES_RESEARCH_TICKS: u32 = TICK_HZ * 20;
pub const METHAMPHETAMINES_SPEED_MULTIPLIER: f32 = 1.25;
pub const METHAMPHETAMINES_ATTACK_COOLDOWN_NUMERATOR: u32 = 3;
pub const METHAMPHETAMINES_ATTACK_COOLDOWN_DENOMINATOR: u32 = 4;
pub const PANZERFAUSTS_COST_STEEL: u32 = 100;
pub const PANZERFAUSTS_COST_OIL: u32 = 100;
pub const PANZERFAUSTS_RESEARCH_TICKS: u32 = TICK_HZ * 20;
pub const ENTRENCHMENT_COST_STEEL: u32 = 200;
pub const ENTRENCHMENT_COST_OIL: u32 = 0;
pub const ENTRENCHMENT_RESEARCH_TICKS: u32 = TICK_HZ * 30;
pub const ANTI_TANK_GUN_UNLOCK_COST_STEEL: u32 = 100;
pub const ANTI_TANK_GUN_UNLOCK_COST_OIL: u32 = 50;
pub const ANTI_TANK_GUN_UNLOCK_RESEARCH_TICKS: u32 = TICK_HZ * 10;
pub const ARTILLERY_UNLOCK_COST_STEEL: u32 = 200;
pub const ARTILLERY_UNLOCK_COST_OIL: u32 = 100;
pub const ARTILLERY_UNLOCK_RESEARCH_TICKS: u32 = TICK_HZ * 25;
pub const BALLISTIC_TABLES_COST_STEEL: u32 = 300;
pub const BALLISTIC_TABLES_COST_OIL: u32 = 200;
pub const BALLISTIC_TABLES_RESEARCH_TICKS: u32 = TICK_HZ * 40;
pub const TANK_UNLOCK_COST_STEEL: u32 = 150;
pub const TANK_UNLOCK_COST_OIL: u32 = 100;
pub const TANK_UNLOCK_RESEARCH_TICKS: u32 = TICK_HZ * 20;
pub const MORTAR_AUTOCAST_COST_STEEL: u32 = 150;
pub const MORTAR_AUTOCAST_COST_OIL: u32 = 150;
pub const MORTAR_AUTOCAST_RESEARCH_TICKS: u32 = TICK_HZ * 20;
pub const SMOKE_PLUS_COST_STEEL: u32 = 150;
pub const SMOKE_PLUS_COST_OIL: u32 = 150;
pub const SMOKE_PLUS_RESEARCH_TICKS: u32 = TICK_HZ * 20;
