// Generated by scripts/art/tank-raster-pipeline.mjs write-atlas.
// The SVG rig remains the source of animation bindings and anchors; this atlas
// only replaces tank part pixels for the prototype raster art path.
function deepFreeze(value) {
  if (!value || typeof value !== "object") return value;
  Object.freeze(value);
  for (const child of Object.values(value)) deepFreeze(child);
  return value;
}

export const TANK_PNG_RIG_ATLAS = deepFreeze({
  "enabled": true,
  "unit": "tank",
  "image": "/assets/rigs/tank-ps1/tank-atlas.png?v=pass06-bright",
  "viewBox": {
    "x": -40,
    "y": -32,
    "width": 80,
    "height": 64
  },
  "grid": {
    "columns": 2,
    "rows": 2,
    "layout": "tight",
    "profile": "semantic",
    "width": 1774,
    "height": 887,
    "sourceSheet": "client/assets/rigs/tank-ps1/generated/tank-tiger-i-pass-06-lowpoly-alpha.png",
    "cells": [
      "reference.full",
      "sprite.track",
      "sprite.hull",
      "sprite.turret"
    ],
    "frameSources": {
      "part.track.left": "sprite.track",
      "part.tread.left.0": "sprite.track",
      "part.tread.left.1": "sprite.track",
      "part.tread.left.2": "sprite.track",
      "part.tread.left.3": "sprite.track",
      "part.tread.left.4": "sprite.track",
      "part.tread.left.5": "sprite.track",
      "part.tread.left.6": "sprite.track",
      "part.tread.left.7": "sprite.track",
      "part.tread.left.8": "sprite.track",
      "part.track.right": "sprite.track",
      "part.tread.right.0": "sprite.track",
      "part.tread.right.1": "sprite.track",
      "part.tread.right.2": "sprite.track",
      "part.tread.right.3": "sprite.track",
      "part.tread.right.4": "sprite.track",
      "part.tread.right.5": "sprite.track",
      "part.tread.right.6": "sprite.track",
      "part.tread.right.7": "sprite.track",
      "part.tread.right.8": "sprite.track",
      "part.hull": "sprite.hull",
      "part.hull.shadow": "sprite.hull",
      "part.hull.nose": "sprite.hull",
      "part.hull.noseShadow": "sprite.hull",
      "part.noseTick": "sprite.hull",
      "part.barrel": "sprite.turret",
      "part.coaxBarrel": "sprite.turret",
      "part.turret": "sprite.turret"
    },
    "normalization": {
      "visibleBounds": true,
      "visiblePadding": 2,
      "clearCellEdgeAlpha": 16,
      "blankCells": [
        "reference.full",
        "sprite.track"
      ]
    },
    "imageVersion": "pass06-bright",
    "colorAdjustment": {
      "brightness": 130,
      "saturation": 105,
      "hue": 100
    }
  },
  "frames": {},
  "sprites": [
    {
      "id": "sprite.track.left",
      "sourceCell": "sprite.track",
      "animationPart": "part.track.left",
      "sourceParts": [
        "part.track.left",
        "part.tread.left.0",
        "part.tread.left.1",
        "part.tread.left.2",
        "part.tread.left.3",
        "part.tread.left.4",
        "part.tread.left.5",
        "part.tread.left.6",
        "part.tread.left.7",
        "part.tread.left.8"
      ],
      "tintSlot": "fixed",
      "drawOrder": 10,
      "frame": {
        "x": 887,
        "y": 0,
        "w": 887,
        "h": 444,
        "originX": 450.5828835489834,
        "originY": 362.4771903881701,
        "pixelsPerUnitX": 11.804805914972274,
        "pixelsPerUnitY": 11.804805914972274
      }
    },
    {
      "id": "sprite.track.right",
      "sourceCell": "sprite.track",
      "animationPart": "part.track.right",
      "sourceParts": [
        "part.track.right",
        "part.tread.right.0",
        "part.tread.right.1",
        "part.tread.right.2",
        "part.tread.right.3",
        "part.tread.right.4",
        "part.tread.right.5",
        "part.tread.right.6",
        "part.tread.right.7",
        "part.tread.right.8"
      ],
      "tintSlot": "fixed",
      "drawOrder": 11,
      "frame": {
        "x": 887,
        "y": 0,
        "w": 887,
        "h": 444,
        "originX": 450.5828835489834,
        "originY": 81.52280961182993,
        "pixelsPerUnitX": 11.804805914972274,
        "pixelsPerUnitY": 11.804805914972274
      }
    },
    {
      "id": "sprite.hull",
      "animationPart": "part.hull",
      "sourceParts": [
        "part.hull",
        "part.hull.shadow",
        "part.hull.nose",
        "part.hull.noseShadow",
        "part.noseTick"
      ],
      "tintSlot": "team",
      "drawOrder": 20,
      "sourceCell": "sprite.hull",
      "frame": {
        "x": 76,
        "y": 496,
        "w": 654,
        "h": 301,
        "visibleBounds": {
          "x": 78,
          "y": 498,
          "w": 650,
          "h": 297
        },
        "originX": 327,
        "originY": 150.5,
        "pixelsPerUnitX": 12.28733459357278,
        "pixelsPerUnitY": 11.739130434782608
      }
    },
    {
      "id": "sprite.turret",
      "animationPart": "part.turret",
      "sourceParts": [
        "part.barrel",
        "part.coaxBarrel",
        "part.turret"
      ],
      "tintSlot": "team-light",
      "drawOrder": 30,
      "sourceCell": "sprite.turret",
      "frame": {
        "x": 982,
        "y": 512,
        "w": 737,
        "h": 272,
        "visibleBounds": {
          "x": 984,
          "y": 514,
          "w": 733,
          "h": 268
        },
        "originX": 155.28751201607966,
        "originY": 136,
        "pixelsPerUnitX": 16.01415712662763,
        "pixelsPerUnitY": 16.791979949874687
      }
    }
  ]
});
