// Generated by scripts/art/tank-raster-pipeline.mjs write-atlas.
// The SVG rig remains the source of animation bindings and anchors; this atlas
// only replaces tank part pixels for the prototype raster art path.
function deepFreeze(value) {
  if (!value || typeof value !== "object") return value;
  Object.freeze(value);
  for (const child of Object.values(value)) deepFreeze(child);
  return value;
}

export const TANK_PNG_RIG_ATLAS = deepFreeze({
  "enabled": true,
  "unit": "tank",
  "image": "/assets/rigs/tank-ps1/tank-atlas.png?v=pass07-separated",
  "viewBox": {
    "x": -40,
    "y": -32,
    "width": 80,
    "height": 64
  },
  "grid": {
    "columns": 2,
    "rows": 3,
    "layout": "tight",
    "profile": "semantic",
    "width": 1145,
    "height": 1373,
    "sourceSheet": "client/assets/rigs/tank-ps1/generated/tank-tiger-i-pass-07-separated-alpha.png",
    "cells": [
      "reference.full",
      "sprite.track",
      "sprite.hull",
      "sprite.turret",
      "sprite.barrel",
      "unused.blank"
    ],
    "frameSources": {
      "part.track.left": "sprite.track",
      "part.tread.left.0": "sprite.track",
      "part.tread.left.1": "sprite.track",
      "part.tread.left.2": "sprite.track",
      "part.tread.left.3": "sprite.track",
      "part.tread.left.4": "sprite.track",
      "part.tread.left.5": "sprite.track",
      "part.tread.left.6": "sprite.track",
      "part.tread.left.7": "sprite.track",
      "part.tread.left.8": "sprite.track",
      "part.track.right": "sprite.track",
      "part.tread.right.0": "sprite.track",
      "part.tread.right.1": "sprite.track",
      "part.tread.right.2": "sprite.track",
      "part.tread.right.3": "sprite.track",
      "part.tread.right.4": "sprite.track",
      "part.tread.right.5": "sprite.track",
      "part.tread.right.6": "sprite.track",
      "part.tread.right.7": "sprite.track",
      "part.tread.right.8": "sprite.track",
      "part.hull": "sprite.hull",
      "part.hull.shadow": "sprite.hull",
      "part.hull.nose": "sprite.hull",
      "part.hull.noseShadow": "sprite.hull",
      "part.noseTick": "sprite.hull",
      "part.coaxBarrel": "sprite.turret",
      "part.turret": "sprite.turret",
      "part.barrel": "sprite.barrel"
    },
    "normalization": {
      "visibleBounds": true,
      "visiblePadding": 2,
      "clearCellEdgeAlpha": 16,
      "blankCells": [
        "reference.full",
        "sprite.track",
        "unused.blank"
      ],
      "ignoreGuideBounds": true,
      "guideMaskFuzz": 30,
      "guideMaskAlphaThreshold": 45,
      "guideMaskLineWidth": 12
    },
    "imageVersion": "pass07-separated",
    "colorAdjustment": {
      "brightness": 120,
      "saturation": 105,
      "hue": 100
    }
  },
  "frames": {},
  "sprites": [
    {
      "id": "sprite.track.left",
      "sourceCell": "sprite.track",
      "animationPart": "part.track.left",
      "sourceParts": [
        "part.track.left",
        "part.tread.left.0",
        "part.tread.left.1",
        "part.tread.left.2",
        "part.tread.left.3",
        "part.tread.left.4",
        "part.tread.left.5",
        "part.tread.left.6",
        "part.tread.left.7",
        "part.tread.left.8"
      ],
      "tintSlot": "fixed",
      "drawOrder": 10,
      "frame": {
        "x": 573,
        "y": 0,
        "w": 572,
        "h": 458,
        "originX": 290.5675415896488,
        "originY": 319.58957486136785,
        "pixelsPerUnitX": 7.6125693160813315,
        "pixelsPerUnitY": 7.6125693160813315
      }
    },
    {
      "id": "sprite.track.right",
      "sourceCell": "sprite.track",
      "animationPart": "part.track.right",
      "sourceParts": [
        "part.track.right",
        "part.tread.right.0",
        "part.tread.right.1",
        "part.tread.right.2",
        "part.tread.right.3",
        "part.tread.right.4",
        "part.tread.right.5",
        "part.tread.right.6",
        "part.tread.right.7",
        "part.tread.right.8"
      ],
      "tintSlot": "fixed",
      "drawOrder": 11,
      "frame": {
        "x": 573,
        "y": 0,
        "w": 572,
        "h": 458,
        "originX": 290.5675415896488,
        "originY": 138.41042513863215,
        "pixelsPerUnitX": 7.6125693160813315,
        "pixelsPerUnitY": 7.6125693160813315
      }
    },
    {
      "id": "sprite.hull",
      "animationPart": "part.hull",
      "sourceParts": [
        "part.hull",
        "part.hull.shadow",
        "part.hull.nose",
        "part.hull.noseShadow",
        "part.noseTick"
      ],
      "tintSlot": "team",
      "drawOrder": 20,
      "sourceCell": "sprite.hull",
      "frame": {
        "x": 91,
        "y": 590,
        "w": 384,
        "h": 193,
        "visibleBounds": {
          "x": 93,
          "y": 592,
          "w": 380,
          "h": 189
        },
        "originX": 192,
        "originY": 96.5,
        "pixelsPerUnitX": 7.183364839319471,
        "pixelsPerUnitY": 7.470355731225296
      }
    },
    {
      "id": "sprite.turret",
      "animationPart": "part.turret",
      "sourceParts": [
        "part.coaxBarrel",
        "part.turret"
      ],
      "tintSlot": "team-light",
      "drawOrder": 30,
      "sourceCell": "sprite.turret",
      "frame": {
        "x": 735,
        "y": 601,
        "w": 192,
        "h": 172,
        "visibleBounds": {
          "x": 737,
          "y": 603,
          "w": 188,
          "h": 168
        },
        "originX": 68.22758722214043,
        "originY": 86,
        "pixelsPerUnitX": 6.918887089651111,
        "pixelsPerUnitY": 10.526315789473683
      }
    },
    {
      "id": "sprite.barrel",
      "animationPart": "part.barrel",
      "sourceParts": [
        "part.barrel"
      ],
      "tintSlot": "fixed",
      "drawOrder": 29,
      "sourceCell": "sprite.barrel",
      "frame": {
        "x": 160,
        "y": 1099,
        "w": 282,
        "h": 67,
        "visibleBounds": {
          "x": 162,
          "y": 1101,
          "w": 278,
          "h": 63
        },
        "originX": 23.27551020408163,
        "originY": 33.5,
        "pixelsPerUnitX": 7.091836734693877,
        "pixelsPerUnitY": 10.5
      }
    }
  ]
});
