// Generated by scripts/art/tank-raster-pipeline.mjs write-atlas.
// The SVG rig remains the source of animation bindings and anchors; this atlas
// only replaces tank part pixels for the prototype raster art path.
function deepFreeze(value) {
  if (!value || typeof value !== "object") return value;
  Object.freeze(value);
  for (const child of Object.values(value)) deepFreeze(child);
  return value;
}

export const TANK_PNG_RIG_ATLAS = deepFreeze({
  "enabled": true,
  "unit": "tank",
  "image": "/assets/rigs/tank-ps1/tank-atlas.png?v=pass08-tiger1",
  "viewBox": {
    "x": -40,
    "y": -32,
    "width": 80,
    "height": 64
  },
  "grid": {
    "columns": 2,
    "rows": 3,
    "layout": "tight",
    "profile": "semantic",
    "width": 1405,
    "height": 1120,
    "sourceSheet": "client/assets/rigs/tank-ps1/generated/tank-tiger-i-pass-08-tiger1-alpha.png",
    "cells": [
      "reference.full",
      "sprite.track",
      "sprite.hull",
      "sprite.turret",
      "sprite.barrel",
      "unused.blank"
    ],
    "frameSources": {
      "part.track.left": "sprite.track",
      "part.tread.left.0": "sprite.track",
      "part.tread.left.1": "sprite.track",
      "part.tread.left.2": "sprite.track",
      "part.tread.left.3": "sprite.track",
      "part.tread.left.4": "sprite.track",
      "part.tread.left.5": "sprite.track",
      "part.tread.left.6": "sprite.track",
      "part.tread.left.7": "sprite.track",
      "part.tread.left.8": "sprite.track",
      "part.track.right": "sprite.track",
      "part.tread.right.0": "sprite.track",
      "part.tread.right.1": "sprite.track",
      "part.tread.right.2": "sprite.track",
      "part.tread.right.3": "sprite.track",
      "part.tread.right.4": "sprite.track",
      "part.tread.right.5": "sprite.track",
      "part.tread.right.6": "sprite.track",
      "part.tread.right.7": "sprite.track",
      "part.tread.right.8": "sprite.track",
      "part.hull": "sprite.hull",
      "part.hull.shadow": "sprite.hull",
      "part.hull.nose": "sprite.hull",
      "part.hull.noseShadow": "sprite.hull",
      "part.noseTick": "sprite.hull",
      "part.coaxBarrel": "sprite.turret",
      "part.turret": "sprite.turret",
      "part.barrel": "sprite.barrel"
    },
    "normalization": {
      "visibleBounds": true,
      "visiblePadding": 2,
      "clearCellEdgeAlpha": 16,
      "blankCells": [
        "reference.full",
        "sprite.track",
        "unused.blank"
      ],
      "ignoreGuideBounds": true,
      "guideMaskFuzz": 12,
      "guideMaskAlphaThreshold": 20,
      "guideMaskLineWidth": 12,
      "guideMaskMorphology": "Square:5"
    },
    "imageVersion": "pass08-tiger1",
    "colorAdjustment": {
      "brightness": 115,
      "saturation": 105,
      "hue": 100
    }
  },
  "frames": {},
  "sprites": [
    {
      "id": "sprite.track.left",
      "sourceCell": "sprite.track",
      "animationPart": "part.track.left",
      "sourceParts": [
        "part.track.left",
        "part.tread.left.0",
        "part.tread.left.1",
        "part.tread.left.2",
        "part.tread.left.3",
        "part.tread.left.4",
        "part.tread.left.5",
        "part.tread.left.6",
        "part.tread.left.7",
        "part.tread.left.8"
      ],
      "tintSlot": "fixed",
      "drawOrder": 10,
      "frame": {
        "x": 703,
        "y": 0,
        "w": 702,
        "h": 373,
        "originX": 356.6056192236599,
        "originY": 297.6781146025878,
        "pixelsPerUnitX": 9.342698706099815,
        "pixelsPerUnitY": 9.342698706099815
      }
    },
    {
      "id": "sprite.track.right",
      "sourceCell": "sprite.track",
      "animationPart": "part.track.right",
      "sourceParts": [
        "part.track.right",
        "part.tread.right.0",
        "part.tread.right.1",
        "part.tread.right.2",
        "part.tread.right.3",
        "part.tread.right.4",
        "part.tread.right.5",
        "part.tread.right.6",
        "part.tread.right.7",
        "part.tread.right.8"
      ],
      "tintSlot": "fixed",
      "drawOrder": 11,
      "frame": {
        "x": 703,
        "y": 0,
        "w": 702,
        "h": 373,
        "originX": 356.6056192236599,
        "originY": 75.32188539741219,
        "pixelsPerUnitX": 9.342698706099815,
        "pixelsPerUnitY": 9.342698706099815
      }
    },
    {
      "id": "sprite.hull",
      "animationPart": "part.hull",
      "sourceParts": [
        "part.hull",
        "part.hull.shadow",
        "part.hull.nose",
        "part.hull.noseShadow",
        "part.noseTick"
      ],
      "tintSlot": "team",
      "drawOrder": 20,
      "sourceCell": "sprite.hull",
      "frame": {
        "x": 103,
        "y": 472,
        "w": 419,
        "h": 178,
        "visibleBounds": {
          "x": 105,
          "y": 474,
          "w": 415,
          "h": 174
        },
        "originX": 209.5,
        "originY": 89,
        "pixelsPerUnitX": 7.844990548204159,
        "pixelsPerUnitY": 6.877470355731225
      }
    },
    {
      "id": "sprite.turret",
      "animationPart": "part.turret",
      "sourceParts": [
        "part.coaxBarrel",
        "part.turret"
      ],
      "tintSlot": "team-light",
      "drawOrder": 30,
      "sourceCell": "sprite.turret",
      "frame": {
        "x": 945,
        "y": 475,
        "w": 225,
        "h": 174,
        "visibleBounds": {
          "x": 947,
          "y": 477,
          "w": 221,
          "h": 170
        },
        "originX": 79.85264242602679,
        "originY": 87,
        "pixelsPerUnitX": 8.133372589430296,
        "pixelsPerUnitY": 10.651629072681704
      }
    },
    {
      "id": "sprite.barrel",
      "animationPart": "part.barrel",
      "sourceParts": [
        "part.barrel"
      ],
      "tintSlot": "team-light",
      "drawOrder": 29,
      "sourceCell": "sprite.barrel",
      "frame": {
        "x": 181,
        "y": 892,
        "w": 342,
        "h": 38,
        "visibleBounds": {
          "x": 183,
          "y": 894,
          "w": 338,
          "h": 34
        },
        "originX": 27.867346938775505,
        "originY": 19,
        "pixelsPerUnitX": 8.622448979591836,
        "pixelsPerUnitY": 5.666666666666667
      }
    }
  ]
});
